# Generated by Django 5.1.6 on 2025-02-28 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
        migrations.DeleteModel(
            name='registro',
        ),
    ]
