# Generated by Django 5.1.6 on 2025-03-01 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0002_delete_login_delete_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='diretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='filme',
            name='diretor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locadora.diretor'),
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=255)),
                ('filmes_alugados', models.ManyToManyField(to='locadora.filme')),
            ],
        ),
    ]
