# Generated by Django 5.1.6 on 2025-03-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0003_diretor_alter_filme_diretor_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='diretor',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='diretor',
        ),
    ]
