# Generated by Django 5.1.6 on 2025-03-01 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0004_alter_filme_diretor_delete_diretor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='filme',
            name='diretor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locadora.diretor'),
        ),
    ]
