# Generated by Django 5.1.6 on 2025-03-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0006_alter_filme_diretor_delete_diretor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='endereco',
            field=models.CharField(default='', max_length=255),
        ),
    ]
