# Generated by Django 5.1.6 on 2025-03-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0007_usuario_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default=123, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default='12342234', max_length=255),
        ),
    ]
