# Generated by Django 5.1.6 on 2025-03-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0008_usuario_last_login_usuario_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=255),
        ),
    ]
