# Generated by Django 5.1.6 on 2025-03-01 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0009_usuario_is_active_usuario_is_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_admin',
        ),
    ]
