# Generated by Django 5.1.6 on 2025-03-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0010_remove_usuario_is_active_remove_usuario_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
