# Generated by Django 5.1.6 on 2025-03-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0011_remove_usuario_senha_usuario_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_superuser',
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
